# Generated by Django 2.2.11 on 2020-03-08 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pergunta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.TextField(verbose_name='Pergunta')),
                ('tipo_pergunta', models.CharField(choices=[('estrelas', 'Estrelas'), ('sim/não', 'Sim/Não'), ('subjetivo', 'Subjetivo')], max_length=10, verbose_name='Tipo de pergunta')),
                ('ativo', models.BooleanField(default=True, verbose_name='Campo Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'perguntas',
            },
        ),
    ]
