# Generated by Django 2.2.11 on 2020-03-08 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('perguntas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resposta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resp_texto', models.TextField(verbose_name='resposta Texto')),
                ('pergunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perguntas.Pergunta')),
            ],
            options={
                'db_table': 'respostas',
            },
        ),
    ]
